### ISSUE TITLE
报错如下，是什么原因呢？

### ISSUE THREAD

**Issue by Pekary** [humiaozuzu/YaH3C#25]
Traceback (most recent call last):
  File "/usr/local/bin/yah3c", line 5, in <module>
    yah3c.yah3c.main()
  File "/usr/local/lib/python2.7/dist-packages/yah3c/yah3c.py", line 126, in main
    start_yah3c(login_info)
  File "/usr/local/lib/python2.7/dist-packages/yah3c/yah3c.py", line 102, in start_yah3c
    yah3c = eapauth.EAPAuth(login_info)
  File "/usr/local/lib/python2.7/dist-packages/yah3c/eapauth.py", line 34, in **init**
    self.client.bind((login_info['ethernet_interface'], ETHERTYPE_PAE))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 19] No such device

**Comment by humiaozuzu** [comment]
已经没有在维护了，你可以去其他 fork 过的人那里寻求帮助。
